// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoList.Repositories.Data;

namespace ToDoList.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ToDoList.Domain.ToDo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("priority");

                    b.Property<int?>("typeToDoid");

                    b.HasKey("id");

                    b.HasIndex("typeToDoid");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("ToDoList.Domain.TypeToDo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("TypeTodos");
                });

            modelBuilder.Entity("ToDoList.Domain.ToDo", b =>
                {
                    b.HasOne("ToDoList.Domain.TypeToDo", "typeToDo")
                        .WithMany("Todos")
                        .HasForeignKey("typeToDoid");
                });
#pragma warning restore 612, 618
        }
    }
}
