// <auto-generated />
using System;
using Aula08CrudPeopleEF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Aula08CrudPeopleEF.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190930225608_AddEntityCity")]
    partial class AddEntityCity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Aula08CrudPeopleEF.Models.Entities.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<int>("age");

                    b.Property<int?>("cityid");

                    b.Property<string>("name");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.HasIndex("cityid");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Aula12CrudPeopleEFComOneToMany.Models.Entities.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Aula08CrudPeopleEF.Models.Entities.Person", b =>
                {
                    b.HasOne("Aula12CrudPeopleEFComOneToMany.Models.Entities.City", "city")
                        .WithMany()
                        .HasForeignKey("cityid");
                });
#pragma warning restore 612, 618
        }
    }
}
